export const LOGIN = 'login'
export const REGISTER = 'register'
export const LOGOUT = 'logout'
export const FETCH_USER_PROFILE = 'fetchUserProfile'
export const FETCH_AVAILABLE_PLUGINS = 'fetchAvailablePlugins'
export const UPDATE_USER_PLUGINS = 'updateUserPlugins'
